screen.columns = 1
screen = [GENERAL] [LIGHTING] [WATER] [FOG] [SKY]

screen.GENERAL = blindnessEffects rainPuddles wetnessHalflife wavingLeaves wavingLeavesStrength wavingLeavesSpeed weatherAffectsWavingLeaves
screen.WATER = wavingWater wavesHaveToSeeSky useBiomeWaterColor waterTexture waterAlpha waterFoam waterFoamDomainWarpedNoise depthBasedWaterFoamStrength generalWaterFoamStrength waterFoamBorder depthBasedWaterFoam generalWaterFoam weatherAffectsWaterEffects waterFoamWidth
screen.LIGHTING = lightWrapping celestialLightStrength skyLightStrength blockLightStrength blockLightAttenuation celestialLightAttenuation
screen.FOG = fogDensity fogDistance strongerNightFog
screen.SKY = skyColorTransitionWidth cbChangeColor customClouds cloudHeightOffset cloudStrength cloudDistance
sliders = wavingLeavesStrength wavingLeavesSpeed waterFoamWidth cloudDistance celestialLightAttenuation cloudStrength cloudHeightOffset wetnessHalflife depthBasedWaterFoamStrength generalWaterFoamStrength waterFoamBorder fogDistance fogDensity skyColorTransitionWidth shadowValue shadowBorder blockLightAttenuation celestialLightStrength waterAlpha skyLightStrength blockLightStrength

uniform.vec3.realCamera = vec3(cameraPosition.x + gbufferModelViewInverse.3.0, cameraPosition.y + gbufferModelViewInverse.3.1, cameraPosition.z + gbufferModelViewInverse.3.2)

underwaterOverlay = false
shadow.enabled = false

#ifdef customClouds
    clouds = off
#endif

particles.ordering=before

customTexture.noisetex0=texture/noise.png

